### ISSUE TITLE
Problem with ssl

### ISSUE THREAD

**Issue by lokize** [iredmail/dockerized#126]
I am not able to make ssl work, I tried to create my own certificate by letsencrypt but every time I restart the container it recreates the certificate and removes the ones I created, which it automatically generates is invalid, is there any way to fix this or disable iredmail to generate a certified every time loaded?

**Comment by koklyk** [comment]
Help, the problem is that I changed the certificate, but it does not work

`Dec 27 19:25:02 mail postfix/submission/smtpd[1140]: connect from unknown[23.106.39.47]
Dec 27 19:25:02 mail postfix/submission/smtpd[1140]: SSL_accept error from unknown[23.106.39.47]: -1
Dec 27 19:25:02 mail postfix/submission/smtpd[1140]: warning: TLS library problem: error:0A000418:SSL routines::tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1584:SSL alert number 48:
Dec 27 19:25:02 mail postfix/submission/smtpd[1140]: lost connection after STARTTLS from unknown[23.106.39.47]
Dec 27 19:25:02 mail postfix/submission/smtpd[1140]: disconnect from unknown[23.106.39.47] ehlo=1 starttls=0/1 commands=1/2`

Mail is sent through mail clients, but does not work through Laravel

how do i set up a mail server?

**Comment by iredmail** [comment]
Is the ssl cert valid when you visit website?

**Comment by koklyk** [comment]
Yes, everything is fine with the certificate and it is valid

**Comment by iredmail** [comment]
What's smtp config in your Laravel app?

**Comment by koklyk** [comment]
OWNSERVER_MAIL_DRIVER=smtp
OWNSERVER_MAIL_HOST=mail.domain.su
OWNSERVER_MAIL_PORT=587
OWNSERVER_MAIL_USERNAME=no-reply@sctp.com.ua
OWNSERVER_MAIL_PASSWORD=*********************
OWNSERVER_MAIL_FROM_ADDRESS=no-reply@domain.su
OWNSERVER_MAIL_FROM_NAME=no-reply
OWNSERVER_MAIL_ENCRYPTION=tls
OWNSERVER_MAIL_CHUNK_SIZE=50

**Comment by lokize** [comment]
???

**Comment by koklyk** [comment]
this is laravel config
Didn't leave real email and password.

**Comment by koklyk** [comment]
The problem was not solved, why was it closed?
