### ISSUE TITLE
Request for production information

### ISSUE THREAD

**Issue by ValentinRgt** [iredmail/dockerized#133]
The message "THIS IS A BETA EDITION AND NOT ALWAYS STABLE, DO NOT TRY IT IN PRODUCTION (YET). "Is it still relevant?
For 1 year and a half, 2 years there is this message, it's still not available for production?

**Comment by daweedm** [comment]
Same question here

**Comment by chenylon** [comment]
All service in a single container is not sensible even someone need this in production.  So if you insist on doing this, I suggest you debug and test the stability of the image by yourself.

**Comment by iredmail** [comment]
The biggest problem with this docker container is how to update SQL databases automatically.

The solution might be easy: add a new table in each database and store current SQL schema version in it, then check it (every time) while launching the container, and apply SQL update(s) if it's an old schema version.

We didn't have time to test it carefully right now, because we're working on a new product which combines iRedMail installer + iRedMail Easy platform + iRedAdmin-Pro, the final product is a single binary since it's written in Golang. FYI  https://docs.iredmail.org/pro.html

**Comment by LunarInterface** [comment]
My guess is that if we separate the database container into docker-compose with the mariadb official version, the script will automatically update the schema inside the mariadb container??

**Comment by ValentinRgt** [comment]
> The biggest problem with this docker container is how to update SQL databases automatically.
> 
> The solution might be easy:
> 
> 1. add a new table in each database and store current SQL schema version in it
> 2. check it (every time) while launching the container
> 3. apply SQL update(s) if it's an old schema version.
> 
> We didn't have enough time to test it carefully right now, because we're focusing on developing a new product which combines iRedMail installer + iRedMail Easy platform + iRedAdmin-Pro, the final product is a single binary since it's written in Golang. FYI https://docs.iredmail.org/pro.html
> 
> Do initial deployment with few clicks, one click update / upgrade / re-deployment, tune server settings (by modifying application config files, not just SQL/LDAP data), etc.

To study the functioning of [Docker Mailserver](https://github.com/docker-mailserver/docker-mailserver) to understand how they do it, maybe it will help you
