### ISSUE TITLE
Roundcube upgrade

### ISSUE THREAD

**Issue by poulwiel** [iredmail/dockerized#147]
Hi all,
is there any plan to upgrade Roundcube version, existing is 1.4.11 which has known voulnerability ([CVE-2023-43770](https://www.cvedetails.com/cve/CVE-2023-43770/)).
I would love to help to upgrade it in the image. I just don't know how to start.
Or maybe the easiest way is to upgrade it inside running docker image as a temporary solution?
If there is someone that can guide me i would be willing to help update it - i've created some docker images for my own use, so there is some level of required knowledge.

**Comment by iredmail** [comment]
Hi @poulwiel 

This github repo is out of date, please don't run it in production.

**Comment by 0xSleipnir** [comment]
Is it somehow foreseeable when the new/working docker image is going to be rolled out for iredmail?
All yet available seem to be outdated/not safe for using in production ... :/

**Comment by iredmail** [comment]
There's a warning message since day one, i don't get it why you guys ignore it:
> WARNING: THIS IS A BETA EDITION AND NOT ALWAYS STABLE, DO NOT TRY IT IN PRODUCTION (YET).

We plan to build a docker image for upcoming iRedMail Enterprise Edition ("EE" for short), since the directory structure is almost same, it's possible to migrate to EE if you're willing to.
https://www.iredmail.org/ee.html
